
SET NAMES utf8mb4;

INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('10961','7','FilterDefinition','15','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11235','7','FilterDefinition','15','1',NULL,NULL,NULL,'false','100','object',NULL,'1',NULL,NULL);
INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11259','7','FilterDefinition','9','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11265','7','FilterDefinition','15','1',NULL,NULL,NULL,'false',NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11266','7','FilterDefinition','15','1',NULL,NULL,NULL,'false',NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11267','7','FilterDefinition','15','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11268','7','FilterDefinition','15','1',NULL,NULL,NULL,'false',NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_query_7 (`oo_id`,`oo_classId`,`oo_className`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`crossSellingCategory__id`,`crossSellingCategory__type`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11275','7','FilterDefinition','9','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
