
SET NAMES utf8mb4;



DROP VIEW IF EXISTS `object_12`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_12` AS select `object_query_12`.`oo_id` AS `oo_id`,`object_query_12`.`oo_classId` AS `oo_classId`,`object_query_12`.`oo_className` AS `oo_className`,`object_query_12`.`artno` AS `artno`,`object_query_12`.`ean` AS `ean`,`object_query_12`.`size` AS `size`,`object_query_12`.`brand__id` AS `brand__id`,`object_query_12`.`brand__type` AS `brand__type`,`object_query_12`.`gender` AS `gender`,`object_query_12`.`categories` AS `categories`,`object_query_12`.`features` AS `features`,`object_query_12`.`technologies` AS `technologies`,`object_query_12`.`attributes` AS `attributes`,`object_query_12`.`collection` AS `collection`,`object_query_12`.`color` AS `color`,`object_query_12`.`materialComposition` AS `materialComposition`,`object_query_12`.`secondaryMaterialComposition` AS `secondaryMaterialComposition`,`object_query_12`.`relatedProducts` AS `relatedProducts`,`object_query_12`.`imagesInheritance` AS `imagesInheritance`,`object_query_12`.`attributesAvailable` AS `attributesAvailable`,`object_query_12`.`variantsAvailable` AS `variantsAvailable`,`object_query_12`.`wfstate` AS `wfstate`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_12` join `objects` on((`objects`.`o_id` = `object_query_12`.`oo_id`)));

DROP VIEW IF EXISTS `object_14`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_14` AS select `object_query_14`.`oo_id` AS `oo_id`,`object_query_14`.`oo_classId` AS `oo_classId`,`object_query_14`.`oo_className` AS `oo_className`,`object_query_14`.`filterdefinition__id` AS `filterdefinition__id`,`object_query_14`.`filterdefinition__type` AS `filterdefinition__type`,`object_query_14`.`priorityProducts` AS `priorityProducts`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_14` join `objects` on((`objects`.`o_id` = `object_query_14`.`oo_id`)));

DROP VIEW IF EXISTS `object_15`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_15` AS select `object_query_15`.`oo_id` AS `oo_id`,`object_query_15`.`oo_classId` AS `oo_classId`,`object_query_15`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_15` join `objects` on((`objects`.`o_id` = `object_query_15`.`oo_id`)));

DROP VIEW IF EXISTS `object_16`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_16` AS select `object_query_16`.`oo_id` AS `oo_id`,`object_query_16`.`oo_classId` AS `oo_classId`,`object_query_16`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_16` join `objects` on((`objects`.`o_id` = `object_query_16`.`oo_id`)));

DROP VIEW IF EXISTS `object_23`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_23` AS select `object_query_23`.`oo_id` AS `oo_id`,`object_query_23`.`oo_classId` AS `oo_classId`,`object_query_23`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_23` join `objects` on((`objects`.`o_id` = `object_query_23`.`oo_id`)));

DROP VIEW IF EXISTS `object_30`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_30` AS select `object_query_30`.`oo_id` AS `oo_id`,`object_query_30`.`oo_classId` AS `oo_classId`,`object_query_30`.`oo_className` AS `oo_className`,`object_query_30`.`totalPrice` AS `totalPrice`,`object_query_30`.`items` AS `items`,`object_query_30`.`offernumber` AS `offernumber`,`object_query_30`.`dateCreated` AS `dateCreated`,`object_query_30`.`dateValidUntil` AS `dateValidUntil`,`object_query_30`.`discount` AS `discount`,`object_query_30`.`customItems` AS `customItems`,`object_query_30`.`discountType` AS `discountType`,`object_query_30`.`cartId` AS `cartId`,`object_query_30`.`totalPriceBeforeDiscount` AS `totalPriceBeforeDiscount`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_30` join `objects` on((`objects`.`o_id` = `object_query_30`.`oo_id`)));

DROP VIEW IF EXISTS `object_31`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_31` AS select `object_query_31`.`oo_id` AS `oo_id`,`object_query_31`.`oo_classId` AS `oo_classId`,`object_query_31`.`oo_className` AS `oo_className`,`object_query_31`.`product__id` AS `product__id`,`object_query_31`.`product__type` AS `product__type`,`object_query_31`.`productNumber` AS `productNumber`,`object_query_31`.`productName` AS `productName`,`object_query_31`.`amount` AS `amount`,`object_query_31`.`subItems` AS `subItems`,`object_query_31`.`comment` AS `comment`,`object_query_31`.`originalTotalPrice` AS `originalTotalPrice`,`object_query_31`.`finalTotalPrice` AS `finalTotalPrice`,`object_query_31`.`discount` AS `discount`,`object_query_31`.`DiscountType` AS `DiscountType`,`object_query_31`.`cartItemKey` AS `cartItemKey`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_31` join `objects` on((`objects`.`o_id` = `object_query_31`.`oo_id`)));

DROP VIEW IF EXISTS `object_32`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_32` AS select `object_query_32`.`oo_id` AS `oo_id`,`object_query_32`.`oo_classId` AS `oo_classId`,`object_query_32`.`oo_className` AS `oo_className`,`object_query_32`.`price` AS `price`,`object_query_32`.`productGroup` AS `productGroup`,`object_query_32`.`OSproductNumber` AS `OSproductNumber`,`object_query_32`.`OSName` AS `OSName`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_32` join `objects` on((`objects`.`o_id` = `object_query_32`.`oo_id`)));

DROP VIEW IF EXISTS `object_33`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_33` AS select `object_query_33`.`oo_id` AS `oo_id`,`object_query_33`.`oo_classId` AS `oo_classId`,`object_query_33`.`oo_className` AS `oo_className`,`object_query_33`.`name` AS `name`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_33` join `objects` on((`objects`.`o_id` = `object_query_33`.`oo_id`)));

DROP VIEW IF EXISTS `object_34`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_34` AS select `object_query_34`.`oo_id` AS `oo_id`,`object_query_34`.`oo_classId` AS `oo_classId`,`object_query_34`.`oo_className` AS `oo_className`,`object_query_34`.`token` AS `token`,`object_query_34`.`tokenId` AS `tokenId`,`object_query_34`.`voucherSeries__id` AS `voucherSeries__id`,`object_query_34`.`voucherSeries__type` AS `voucherSeries__type`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_34` join `objects` on((`objects`.`o_id` = `object_query_34`.`oo_id`)));

DROP VIEW IF EXISTS `object_35`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_35` AS select `object_query_35`.`oo_id` AS `oo_id`,`object_query_35`.`oo_classId` AS `oo_classId`,`object_query_35`.`oo_className` AS `oo_className`,`object_query_35`.`taxEntryCombinationType` AS `taxEntryCombinationType`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_35` join `objects` on((`objects`.`o_id` = `object_query_35`.`oo_id`)));

DROP VIEW IF EXISTS `object_36`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_36` AS select `object_query_36`.`oo_id` AS `oo_id`,`object_query_36`.`oo_classId` AS `oo_classId`,`object_query_36`.`oo_className` AS `oo_className`,`object_query_36`.`name` AS `name`,`object_query_36`.`reference` AS `reference`,`object_query_36`.`calculated` AS `calculated`,`object_query_36`.`showAsFilter` AS `showAsFilter`,`object_query_36`.`exportNewsletterProvider` AS `exportNewsletterProvider`,`object_query_36`.`filterSortOrder` AS `filterSortOrder`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_36` join `objects` on((`objects`.`o_id` = `object_query_36`.`oo_id`)));

DROP VIEW IF EXISTS `object_37`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_37` AS select `object_query_37`.`oo_id` AS `oo_id`,`object_query_37`.`oo_classId` AS `oo_classId`,`object_query_37`.`oo_className` AS `oo_className`,`object_query_37`.`name` AS `name`,`object_query_37`.`group__id` AS `group__id`,`object_query_37`.`group__type` AS `group__type`,`object_query_37`.`reference` AS `reference`,`object_query_37`.`calculated` AS `calculated`,`object_query_37`.`useAsTargetGroup` AS `useAsTargetGroup`,`object_query_37`.`targetGroup` AS `targetGroup`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_37` join `objects` on((`objects`.`o_id` = `object_query_37`.`oo_id`)));

DROP VIEW IF EXISTS `object_38`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_38` AS select `object_query_38`.`oo_id` AS `oo_id`,`object_query_38`.`oo_classId` AS `oo_classId`,`object_query_38`.`oo_className` AS `oo_className`,`object_query_38`.`provider` AS `provider`,`object_query_38`.`identifier` AS `identifier`,`object_query_38`.`profileData` AS `profileData`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_38` join `objects` on((`objects`.`o_id` = `object_query_38`.`oo_id`)));

DROP VIEW IF EXISTS `object_39`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_39` AS select `object_query_39`.`oo_id` AS `oo_id`,`object_query_39`.`oo_classId` AS `oo_classId`,`object_query_39`.`oo_className` AS `oo_className`,`object_query_39`.`name` AS `name`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_39` join `objects` on((`objects`.`o_id` = `object_query_39`.`oo_id`)));

DROP VIEW IF EXISTS `object_40`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_40` AS select `object_query_40`.`oo_id` AS `oo_id`,`object_query_40`.`oo_classId` AS `oo_classId`,`object_query_40`.`oo_className` AS `oo_className`,`object_query_40`.`code` AS `code`,`object_query_40`.`attributeType` AS `attributeType`,`object_query_40`.`label` AS `label`,`object_query_40`.`link` AS `link`,`object_query_40`.`active` AS `active`,`object_query_40`.`utm_source` AS `utm_source`,`object_query_40`.`utm_medium` AS `utm_medium`,`object_query_40`.`utm_campaign` AS `utm_campaign`,`object_query_40`.`utm_term` AS `utm_term`,`object_query_40`.`utm_content` AS `utm_content`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_40` join `objects` on((`objects`.`o_id` = `object_query_40`.`oo_id`)));

DROP VIEW IF EXISTS `object_41`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_41` AS select `object_query_41`.`oo_id` AS `oo_id`,`object_query_41`.`oo_classId` AS `oo_classId`,`object_query_41`.`oo_className` AS `oo_className`,`object_query_41`.`active` AS `active`,`object_query_41`.`gender` AS `gender`,`object_query_41`.`firstname` AS `firstname`,`object_query_41`.`lastname` AS `lastname`,`object_query_41`.`street` AS `street`,`object_query_41`.`zip` AS `zip`,`object_query_41`.`city` AS `city`,`object_query_41`.`countryCode` AS `countryCode`,`object_query_41`.`email` AS `email`,`object_query_41`.`phone` AS `phone`,`object_query_41`.`manualSegments` AS `manualSegments`,`object_query_41`.`calculatedSegments` AS `calculatedSegments`,`object_query_41`.`idEncoded` AS `idEncoded`,`object_query_41`.`password` AS `password`,`object_query_41`.`ssoIdentities` AS `ssoIdentities`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_41` join `objects` on((`objects`.`o_id` = `object_query_41`.`oo_id`)));

DROP VIEW IF EXISTS `object_7`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_7` AS select `object_query_7`.`oo_id` AS `oo_id`,`object_query_7`.`oo_classId` AS `oo_classId`,`object_query_7`.`oo_className` AS `oo_className`,`object_query_7`.`pageLimit` AS `pageLimit`,`object_query_7`.`ajaxReload` AS `ajaxReload`,`object_query_7`.`limitOnFirstLoad` AS `limitOnFirstLoad`,`object_query_7`.`defaultOrderByInheritance` AS `defaultOrderByInheritance`,`object_query_7`.`conditionsInheritance` AS `conditionsInheritance`,`object_query_7`.`filtersInheritance` AS `filtersInheritance`,`object_query_7`.`crossSellingCategory__id` AS `crossSellingCategory__id`,`object_query_7`.`crossSellingCategory__type` AS `crossSellingCategory__type`,`object_query_7`.`similarityFieldsInheritance` AS `similarityFieldsInheritance`,`object_query_7`.`infiniteScroll` AS `infiniteScroll`,`object_query_7`.`orderByAsc` AS `orderByAsc`,`object_query_7`.`orderByDesc` AS `orderByDesc`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_7` join `objects` on((`objects`.`o_id` = `object_query_7`.`oo_id`)));

DROP VIEW IF EXISTS `object_8`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_8` AS select `object_query_8`.`oo_id` AS `oo_id`,`object_query_8`.`oo_classId` AS `oo_classId`,`object_query_8`.`oo_className` AS `oo_className`,`object_query_8`.`product__id` AS `product__id`,`object_query_8`.`product__type` AS `product__type`,`object_query_8`.`productNumber` AS `productNumber`,`object_query_8`.`productName` AS `productName`,`object_query_8`.`amount` AS `amount`,`object_query_8`.`totalPrice` AS `totalPrice`,`object_query_8`.`subItems` AS `subItems`,`object_query_8`.`comment` AS `comment`,`object_query_8`.`orderState` AS `orderState`,`object_query_8`.`totalNetPrice` AS `totalNetPrice`,`object_query_8`.`taxInfo` AS `taxInfo`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_8` join `objects` on((`objects`.`o_id` = `object_query_8`.`oo_id`)));

DROP VIEW IF EXISTS `object_9`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_9` AS select `object_query_9`.`oo_id` AS `oo_id`,`object_query_9`.`oo_classId` AS `oo_classId`,`object_query_9`.`oo_className` AS `oo_className`,`object_query_9`.`ordernumber` AS `ordernumber`,`object_query_9`.`totalPrice` AS `totalPrice`,`object_query_9`.`orderdate` AS `orderdate`,`object_query_9`.`items` AS `items`,`object_query_9`.`customer__id` AS `customer__id`,`object_query_9`.`customer__type` AS `customer__type`,`object_query_9`.`paymentReference` AS `paymentReference`,`object_query_9`.`orderState` AS `orderState`,`object_query_9`.`cartId` AS `cartId`,`object_query_9`.`customerOrderData` AS `customerOrderData`,`object_query_9`.`currency` AS `currency`,`object_query_9`.`comment` AS `comment`,`object_query_9`.`customerCompany` AS `customerCompany`,`object_query_9`.`customerStreet` AS `customerStreet`,`object_query_9`.`customerZip` AS `customerZip`,`object_query_9`.`customerCountry` AS `customerCountry`,`object_query_9`.`customerEmail` AS `customerEmail`,`object_query_9`.`deliveryCompany` AS `deliveryCompany`,`object_query_9`.`deliveryStreet` AS `deliveryStreet`,`object_query_9`.`deliveryZip` AS `deliveryZip`,`object_query_9`.`deliveryCity` AS `deliveryCity`,`object_query_9`.`deliveryCountry` AS `deliveryCountry`,`object_query_9`.`voucherTokens` AS `voucherTokens`,`object_query_9`.`customerCity` AS `customerCity`,`object_query_9`.`subTotalPrice` AS `subTotalPrice`,`object_query_9`.`customerFirstname` AS `customerFirstname`,`object_query_9`.`customerLastname` AS `customerLastname`,`object_query_9`.`deliveryLastname` AS `deliveryLastname`,`object_query_9`.`deliveryFirstname` AS `deliveryFirstname`,`object_query_9`.`giftItems` AS `giftItems`,`object_query_9`.`subTotalNetPrice` AS `subTotalNetPrice`,`object_query_9`.`totalNetPrice` AS `totalNetPrice`,`object_query_9`.`taxInfo` AS `taxInfo`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount` from (`object_query_9` join `objects` on((`objects`.`o_id` = `object_query_9`.`oo_id`)));

DROP VIEW IF EXISTS `object_localized_12_de_AT`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_12_de_AT` AS select `object_query_12`.`oo_id` AS `oo_id`,`object_query_12`.`oo_classId` AS `oo_classId`,`object_query_12`.`oo_className` AS `oo_className`,`object_query_12`.`artno` AS `artno`,`object_query_12`.`ean` AS `ean`,`object_query_12`.`size` AS `size`,`object_query_12`.`brand__id` AS `brand__id`,`object_query_12`.`brand__type` AS `brand__type`,`object_query_12`.`gender` AS `gender`,`object_query_12`.`categories` AS `categories`,`object_query_12`.`features` AS `features`,`object_query_12`.`technologies` AS `technologies`,`object_query_12`.`attributes` AS `attributes`,`object_query_12`.`collection` AS `collection`,`object_query_12`.`color` AS `color`,`object_query_12`.`materialComposition` AS `materialComposition`,`object_query_12`.`secondaryMaterialComposition` AS `secondaryMaterialComposition`,`object_query_12`.`relatedProducts` AS `relatedProducts`,`object_query_12`.`imagesInheritance` AS `imagesInheritance`,`object_query_12`.`attributesAvailable` AS `attributesAvailable`,`object_query_12`.`variantsAvailable` AS `variantsAvailable`,`object_query_12`.`wfstate` AS `wfstate`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`de_AT`.`ooo_id` AS `ooo_id`,`de_AT`.`language` AS `language`,`de_AT`.`name` AS `name`,`de_AT`.`seoname` AS `seoname`,`de_AT`.`colorName` AS `colorName`,`de_AT`.`price` AS `price`,`de_AT`.`priceOld` AS `priceOld`,`de_AT`.`fromPrice` AS `fromPrice`,`de_AT`.`description` AS `description`,`de_AT`.`material` AS `material`,`de_AT`.`downloads` AS `downloads`,`de_AT`.`videos` AS `videos`,`de_AT`.`rotation__id` AS `rotation__id`,`de_AT`.`rotation__type` AS `rotation__type`,`de_AT`.`youtubeVideo` AS `youtubeVideo`,`de_AT`.`textsAvailable` AS `textsAvailable` from ((`object_query_12` join `objects` on((`objects`.`o_id` = `object_query_12`.`oo_id`))) left join `object_localized_query_12_de_AT` `de_AT` on((1 and (`object_query_12`.`oo_id` = `de_AT`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_12_default`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_12_default` AS select `object_query_12`.`oo_id` AS `oo_id`,`object_query_12`.`oo_classId` AS `oo_classId`,`object_query_12`.`oo_className` AS `oo_className`,`object_query_12`.`artno` AS `artno`,`object_query_12`.`ean` AS `ean`,`object_query_12`.`size` AS `size`,`object_query_12`.`brand__id` AS `brand__id`,`object_query_12`.`brand__type` AS `brand__type`,`object_query_12`.`gender` AS `gender`,`object_query_12`.`categories` AS `categories`,`object_query_12`.`features` AS `features`,`object_query_12`.`technologies` AS `technologies`,`object_query_12`.`attributes` AS `attributes`,`object_query_12`.`collection` AS `collection`,`object_query_12`.`color` AS `color`,`object_query_12`.`materialComposition` AS `materialComposition`,`object_query_12`.`secondaryMaterialComposition` AS `secondaryMaterialComposition`,`object_query_12`.`relatedProducts` AS `relatedProducts`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,group_concat(`object_localized_data_12`.`name` separator ',') AS `name`,group_concat(`object_localized_data_12`.`seoname` separator ',') AS `seoname`,group_concat(`object_localized_data_12`.`colorName` separator ',') AS `colorName`,group_concat(`object_localized_data_12`.`price` separator ',') AS `price`,group_concat(`object_localized_data_12`.`priceOld` separator ',') AS `priceOld`,group_concat(`object_localized_data_12`.`fromPrice` separator ',') AS `fromPrice`,group_concat(`object_localized_data_12`.`description` separator ',') AS `description`,group_concat(`object_localized_data_12`.`material` separator ',') AS `material`,group_concat(`object_localized_data_12`.`youtubeVideo` separator ',') AS `youtubeVideo` from ((`object_query_12` join `objects` on((`objects`.`o_id` = `object_query_12`.`oo_id`))) left join `object_localized_data_12` on((`objects`.`o_id` = `object_localized_data_12`.`ooo_id`))) group by `objects`.`o_id`;

DROP VIEW IF EXISTS `object_localized_12_en`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_12_en` AS select `object_query_12`.`oo_id` AS `oo_id`,`object_query_12`.`oo_classId` AS `oo_classId`,`object_query_12`.`oo_className` AS `oo_className`,`object_query_12`.`artno` AS `artno`,`object_query_12`.`ean` AS `ean`,`object_query_12`.`size` AS `size`,`object_query_12`.`brand__id` AS `brand__id`,`object_query_12`.`brand__type` AS `brand__type`,`object_query_12`.`gender` AS `gender`,`object_query_12`.`categories` AS `categories`,`object_query_12`.`features` AS `features`,`object_query_12`.`technologies` AS `technologies`,`object_query_12`.`attributes` AS `attributes`,`object_query_12`.`collection` AS `collection`,`object_query_12`.`color` AS `color`,`object_query_12`.`materialComposition` AS `materialComposition`,`object_query_12`.`secondaryMaterialComposition` AS `secondaryMaterialComposition`,`object_query_12`.`relatedProducts` AS `relatedProducts`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`object_localized_data_12`.`ooo_id` AS `ooo_id`,`object_localized_data_12`.`language` AS `language`,`object_localized_data_12`.`name` AS `name`,`object_localized_data_12`.`seoname` AS `seoname`,`object_localized_data_12`.`colorName` AS `colorName`,`object_localized_data_12`.`price` AS `price`,`object_localized_data_12`.`priceOld` AS `priceOld`,`object_localized_data_12`.`fromPrice` AS `fromPrice`,`object_localized_data_12`.`description` AS `description`,`object_localized_data_12`.`material` AS `material`,`object_localized_data_12`.`youtubeVideo` AS `youtubeVideo` from ((`object_query_12` join `objects` on((`objects`.`o_id` = `object_query_12`.`oo_id`))) left join `object_localized_data_12` on(((`object_query_12`.`oo_id` = `object_localized_data_12`.`ooo_id`) and (`object_localized_data_12`.`language` = 'en'))));

DROP VIEW IF EXISTS `object_localized_12_en_GB`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_12_en_GB` AS select `object_query_12`.`oo_id` AS `oo_id`,`object_query_12`.`oo_classId` AS `oo_classId`,`object_query_12`.`oo_className` AS `oo_className`,`object_query_12`.`artno` AS `artno`,`object_query_12`.`ean` AS `ean`,`object_query_12`.`size` AS `size`,`object_query_12`.`brand__id` AS `brand__id`,`object_query_12`.`brand__type` AS `brand__type`,`object_query_12`.`gender` AS `gender`,`object_query_12`.`categories` AS `categories`,`object_query_12`.`features` AS `features`,`object_query_12`.`technologies` AS `technologies`,`object_query_12`.`attributes` AS `attributes`,`object_query_12`.`collection` AS `collection`,`object_query_12`.`color` AS `color`,`object_query_12`.`materialComposition` AS `materialComposition`,`object_query_12`.`secondaryMaterialComposition` AS `secondaryMaterialComposition`,`object_query_12`.`relatedProducts` AS `relatedProducts`,`object_query_12`.`imagesInheritance` AS `imagesInheritance`,`object_query_12`.`attributesAvailable` AS `attributesAvailable`,`object_query_12`.`variantsAvailable` AS `variantsAvailable`,`object_query_12`.`wfstate` AS `wfstate`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`en_GB`.`ooo_id` AS `ooo_id`,`en_GB`.`language` AS `language`,`en_GB`.`name` AS `name`,`en_GB`.`seoname` AS `seoname`,`en_GB`.`colorName` AS `colorName`,`en_GB`.`price` AS `price`,`en_GB`.`priceOld` AS `priceOld`,`en_GB`.`fromPrice` AS `fromPrice`,`en_GB`.`description` AS `description`,`en_GB`.`material` AS `material`,`en_GB`.`downloads` AS `downloads`,`en_GB`.`videos` AS `videos`,`en_GB`.`rotation__id` AS `rotation__id`,`en_GB`.`rotation__type` AS `rotation__type`,`en_GB`.`youtubeVideo` AS `youtubeVideo`,`en_GB`.`textsAvailable` AS `textsAvailable` from ((`object_query_12` join `objects` on((`objects`.`o_id` = `object_query_12`.`oo_id`))) left join `object_localized_query_12_en_GB` `en_GB` on((1 and (`object_query_12`.`oo_id` = `en_GB`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_12_fr_FR`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_12_fr_FR` AS select `object_query_12`.`oo_id` AS `oo_id`,`object_query_12`.`oo_classId` AS `oo_classId`,`object_query_12`.`oo_className` AS `oo_className`,`object_query_12`.`artno` AS `artno`,`object_query_12`.`ean` AS `ean`,`object_query_12`.`size` AS `size`,`object_query_12`.`brand__id` AS `brand__id`,`object_query_12`.`brand__type` AS `brand__type`,`object_query_12`.`gender` AS `gender`,`object_query_12`.`categories` AS `categories`,`object_query_12`.`features` AS `features`,`object_query_12`.`technologies` AS `technologies`,`object_query_12`.`attributes` AS `attributes`,`object_query_12`.`collection` AS `collection`,`object_query_12`.`color` AS `color`,`object_query_12`.`materialComposition` AS `materialComposition`,`object_query_12`.`secondaryMaterialComposition` AS `secondaryMaterialComposition`,`object_query_12`.`relatedProducts` AS `relatedProducts`,`object_query_12`.`imagesInheritance` AS `imagesInheritance`,`object_query_12`.`attributesAvailable` AS `attributesAvailable`,`object_query_12`.`variantsAvailable` AS `variantsAvailable`,`object_query_12`.`wfstate` AS `wfstate`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`fr_FR`.`ooo_id` AS `ooo_id`,`fr_FR`.`language` AS `language`,`fr_FR`.`name` AS `name`,`fr_FR`.`seoname` AS `seoname`,`fr_FR`.`colorName` AS `colorName`,`fr_FR`.`price` AS `price`,`fr_FR`.`priceOld` AS `priceOld`,`fr_FR`.`fromPrice` AS `fromPrice`,`fr_FR`.`description` AS `description`,`fr_FR`.`material` AS `material`,`fr_FR`.`downloads` AS `downloads`,`fr_FR`.`videos` AS `videos`,`fr_FR`.`rotation__id` AS `rotation__id`,`fr_FR`.`rotation__type` AS `rotation__type`,`fr_FR`.`youtubeVideo` AS `youtubeVideo`,`fr_FR`.`textsAvailable` AS `textsAvailable` from ((`object_query_12` join `objects` on((`objects`.`o_id` = `object_query_12`.`oo_id`))) left join `object_localized_query_12_fr_FR` `fr_FR` on((1 and (`object_query_12`.`oo_id` = `fr_FR`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_14_de_AT`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_14_de_AT` AS select `object_query_14`.`oo_id` AS `oo_id`,`object_query_14`.`oo_classId` AS `oo_classId`,`object_query_14`.`oo_className` AS `oo_className`,`object_query_14`.`filterdefinition__id` AS `filterdefinition__id`,`object_query_14`.`filterdefinition__type` AS `filterdefinition__type`,`object_query_14`.`priorityProducts` AS `priorityProducts`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`de_AT`.`ooo_id` AS `ooo_id`,`de_AT`.`language` AS `language`,`de_AT`.`image` AS `image`,`de_AT`.`name` AS `name`,`de_AT`.`seoname` AS `seoname`,`de_AT`.`seotext` AS `seotext`,`de_AT`.`sortkey` AS `sortkey` from ((`object_query_14` join `objects` on((`objects`.`o_id` = `object_query_14`.`oo_id`))) left join `object_localized_query_14_de_AT` `de_AT` on((1 and (`object_query_14`.`oo_id` = `de_AT`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_14_en_GB`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_14_en_GB` AS select `object_query_14`.`oo_id` AS `oo_id`,`object_query_14`.`oo_classId` AS `oo_classId`,`object_query_14`.`oo_className` AS `oo_className`,`object_query_14`.`filterdefinition__id` AS `filterdefinition__id`,`object_query_14`.`filterdefinition__type` AS `filterdefinition__type`,`object_query_14`.`priorityProducts` AS `priorityProducts`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`en_GB`.`ooo_id` AS `ooo_id`,`en_GB`.`language` AS `language`,`en_GB`.`image` AS `image`,`en_GB`.`name` AS `name`,`en_GB`.`seoname` AS `seoname`,`en_GB`.`seotext` AS `seotext`,`en_GB`.`sortkey` AS `sortkey` from ((`object_query_14` join `objects` on((`objects`.`o_id` = `object_query_14`.`oo_id`))) left join `object_localized_query_14_en_GB` `en_GB` on((1 and (`object_query_14`.`oo_id` = `en_GB`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_14_fr_FR`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_14_fr_FR` AS select `object_query_14`.`oo_id` AS `oo_id`,`object_query_14`.`oo_classId` AS `oo_classId`,`object_query_14`.`oo_className` AS `oo_className`,`object_query_14`.`filterdefinition__id` AS `filterdefinition__id`,`object_query_14`.`filterdefinition__type` AS `filterdefinition__type`,`object_query_14`.`priorityProducts` AS `priorityProducts`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`fr_FR`.`ooo_id` AS `ooo_id`,`fr_FR`.`language` AS `language`,`fr_FR`.`image` AS `image`,`fr_FR`.`name` AS `name`,`fr_FR`.`seoname` AS `seoname`,`fr_FR`.`seotext` AS `seotext`,`fr_FR`.`sortkey` AS `sortkey` from ((`object_query_14` join `objects` on((`objects`.`o_id` = `object_query_14`.`oo_id`))) left join `object_localized_query_14_fr_FR` `fr_FR` on((1 and (`object_query_14`.`oo_id` = `fr_FR`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_15_de_AT`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_15_de_AT` AS select `object_query_15`.`oo_id` AS `oo_id`,`object_query_15`.`oo_classId` AS `oo_classId`,`object_query_15`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`de_AT`.`ooo_id` AS `ooo_id`,`de_AT`.`language` AS `language`,`de_AT`.`name` AS `name`,`de_AT`.`description` AS `description`,`de_AT`.`icon` AS `icon`,`de_AT`.`usage` AS `usage` from ((`object_query_15` join `objects` on((`objects`.`o_id` = `object_query_15`.`oo_id`))) left join `object_localized_query_15_de_AT` `de_AT` on((1 and (`object_query_15`.`oo_id` = `de_AT`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_15_default`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_15_default` AS select `object_query_15`.`oo_id` AS `oo_id`,`object_query_15`.`oo_classId` AS `oo_classId`,`object_query_15`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,group_concat(`object_localized_data_15`.`name` separator ',') AS `name`,group_concat(`object_localized_data_15`.`description` separator ',') AS `description`,group_concat(`object_localized_data_15`.`icon` separator ',') AS `icon`,group_concat(`object_localized_data_15`.`usage` separator ',') AS `usage` from ((`object_query_15` join `objects` on((`objects`.`o_id` = `object_query_15`.`oo_id`))) left join `object_localized_data_15` on((`objects`.`o_id` = `object_localized_data_15`.`ooo_id`))) group by `objects`.`o_id`;

DROP VIEW IF EXISTS `object_localized_15_en`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_15_en` AS select `object_query_15`.`oo_id` AS `oo_id`,`object_query_15`.`oo_classId` AS `oo_classId`,`object_query_15`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`object_localized_data_15`.`ooo_id` AS `ooo_id`,`object_localized_data_15`.`language` AS `language`,`object_localized_data_15`.`name` AS `name`,`object_localized_data_15`.`description` AS `description`,`object_localized_data_15`.`icon` AS `icon`,`object_localized_data_15`.`usage` AS `usage` from ((`object_query_15` join `objects` on((`objects`.`o_id` = `object_query_15`.`oo_id`))) left join `object_localized_data_15` on(((`object_query_15`.`oo_id` = `object_localized_data_15`.`ooo_id`) and (`object_localized_data_15`.`language` = 'en'))));

DROP VIEW IF EXISTS `object_localized_15_en_GB`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_15_en_GB` AS select `object_query_15`.`oo_id` AS `oo_id`,`object_query_15`.`oo_classId` AS `oo_classId`,`object_query_15`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`en_GB`.`ooo_id` AS `ooo_id`,`en_GB`.`language` AS `language`,`en_GB`.`name` AS `name`,`en_GB`.`description` AS `description`,`en_GB`.`icon` AS `icon`,`en_GB`.`usage` AS `usage` from ((`object_query_15` join `objects` on((`objects`.`o_id` = `object_query_15`.`oo_id`))) left join `object_localized_query_15_en_GB` `en_GB` on((1 and (`object_query_15`.`oo_id` = `en_GB`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_15_fr_FR`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_15_fr_FR` AS select `object_query_15`.`oo_id` AS `oo_id`,`object_query_15`.`oo_classId` AS `oo_classId`,`object_query_15`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`fr_FR`.`ooo_id` AS `ooo_id`,`fr_FR`.`language` AS `language`,`fr_FR`.`name` AS `name`,`fr_FR`.`description` AS `description`,`fr_FR`.`icon` AS `icon`,`fr_FR`.`usage` AS `usage` from ((`object_query_15` join `objects` on((`objects`.`o_id` = `object_query_15`.`oo_id`))) left join `object_localized_query_15_fr_FR` `fr_FR` on((1 and (`object_query_15`.`oo_id` = `fr_FR`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_16_de_AT`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_16_de_AT` AS select `object_query_16`.`oo_id` AS `oo_id`,`object_query_16`.`oo_classId` AS `oo_classId`,`object_query_16`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`de_AT`.`ooo_id` AS `ooo_id`,`de_AT`.`language` AS `language`,`de_AT`.`icon` AS `icon`,`de_AT`.`name` AS `name`,`de_AT`.`seoname` AS `seoname`,`de_AT`.`description` AS `description`,`de_AT`.`link` AS `link`,`de_AT`.`images` AS `images`,`de_AT`.`documents` AS `documents`,`de_AT`.`videos` AS `videos`,`de_AT`.`downloads` AS `downloads` from ((`object_query_16` join `objects` on((`objects`.`o_id` = `object_query_16`.`oo_id`))) left join `object_localized_query_16_de_AT` `de_AT` on((1 and (`object_query_16`.`oo_id` = `de_AT`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_16_default`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_16_default` AS select `object_query_16`.`oo_id` AS `oo_id`,`object_query_16`.`oo_classId` AS `oo_classId`,`object_query_16`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,group_concat(`object_localized_data_16`.`icon` separator ',') AS `icon`,group_concat(`object_localized_data_16`.`name` separator ',') AS `name`,group_concat(`object_localized_data_16`.`seoname` separator ',') AS `seoname`,group_concat(`object_localized_data_16`.`description` separator ',') AS `description`,group_concat(`object_localized_data_16`.`link` separator ',') AS `link` from ((`object_query_16` join `objects` on((`objects`.`o_id` = `object_query_16`.`oo_id`))) left join `object_localized_data_16` on((`objects`.`o_id` = `object_localized_data_16`.`ooo_id`))) group by `objects`.`o_id`;

DROP VIEW IF EXISTS `object_localized_16_en`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_16_en` AS select `object_query_16`.`oo_id` AS `oo_id`,`object_query_16`.`oo_classId` AS `oo_classId`,`object_query_16`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`object_localized_data_16`.`ooo_id` AS `ooo_id`,`object_localized_data_16`.`language` AS `language`,`object_localized_data_16`.`icon` AS `icon`,`object_localized_data_16`.`name` AS `name`,`object_localized_data_16`.`seoname` AS `seoname`,`object_localized_data_16`.`description` AS `description`,`object_localized_data_16`.`link` AS `link` from ((`object_query_16` join `objects` on((`objects`.`o_id` = `object_query_16`.`oo_id`))) left join `object_localized_data_16` on(((`object_query_16`.`oo_id` = `object_localized_data_16`.`ooo_id`) and (`object_localized_data_16`.`language` = 'en'))));

DROP VIEW IF EXISTS `object_localized_16_en_GB`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_16_en_GB` AS select `object_query_16`.`oo_id` AS `oo_id`,`object_query_16`.`oo_classId` AS `oo_classId`,`object_query_16`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`en_GB`.`ooo_id` AS `ooo_id`,`en_GB`.`language` AS `language`,`en_GB`.`icon` AS `icon`,`en_GB`.`name` AS `name`,`en_GB`.`seoname` AS `seoname`,`en_GB`.`description` AS `description`,`en_GB`.`link` AS `link`,`en_GB`.`images` AS `images`,`en_GB`.`documents` AS `documents`,`en_GB`.`videos` AS `videos`,`en_GB`.`downloads` AS `downloads` from ((`object_query_16` join `objects` on((`objects`.`o_id` = `object_query_16`.`oo_id`))) left join `object_localized_query_16_en_GB` `en_GB` on((1 and (`object_query_16`.`oo_id` = `en_GB`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_16_fr_FR`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_16_fr_FR` AS select `object_query_16`.`oo_id` AS `oo_id`,`object_query_16`.`oo_classId` AS `oo_classId`,`object_query_16`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`fr_FR`.`ooo_id` AS `ooo_id`,`fr_FR`.`language` AS `language`,`fr_FR`.`icon` AS `icon`,`fr_FR`.`name` AS `name`,`fr_FR`.`seoname` AS `seoname`,`fr_FR`.`description` AS `description`,`fr_FR`.`link` AS `link`,`fr_FR`.`images` AS `images`,`fr_FR`.`documents` AS `documents`,`fr_FR`.`videos` AS `videos`,`fr_FR`.`downloads` AS `downloads` from ((`object_query_16` join `objects` on((`objects`.`o_id` = `object_query_16`.`oo_id`))) left join `object_localized_query_16_fr_FR` `fr_FR` on((1 and (`object_query_16`.`oo_id` = `fr_FR`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_23_de_AT`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_23_de_AT` AS select `object_query_23`.`oo_id` AS `oo_id`,`object_query_23`.`oo_classId` AS `oo_classId`,`object_query_23`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`de_AT`.`ooo_id` AS `ooo_id`,`de_AT`.`language` AS `language`,`de_AT`.`icon` AS `icon`,`de_AT`.`name` AS `name`,`de_AT`.`seoname` AS `seoname`,`de_AT`.`description` AS `description`,`de_AT`.`link` AS `link`,`de_AT`.`images` AS `images`,`de_AT`.`documents` AS `documents`,`de_AT`.`videos` AS `videos`,`de_AT`.`downloads` AS `downloads` from ((`object_query_23` join `objects` on((`objects`.`o_id` = `object_query_23`.`oo_id`))) left join `object_localized_query_23_de_AT` `de_AT` on((1 and (`object_query_23`.`oo_id` = `de_AT`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_23_default`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_23_default` AS select `object_query_23`.`oo_id` AS `oo_id`,`object_query_23`.`oo_classId` AS `oo_classId`,`object_query_23`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,group_concat(`object_localized_data_23`.`icon` separator ',') AS `icon`,group_concat(`object_localized_data_23`.`name` separator ',') AS `name`,group_concat(`object_localized_data_23`.`seoname` separator ',') AS `seoname`,group_concat(`object_localized_data_23`.`description` separator ',') AS `description`,group_concat(`object_localized_data_23`.`link` separator ',') AS `link` from ((`object_query_23` join `objects` on((`objects`.`o_id` = `object_query_23`.`oo_id`))) left join `object_localized_data_23` on((`objects`.`o_id` = `object_localized_data_23`.`ooo_id`))) group by `objects`.`o_id`;

DROP VIEW IF EXISTS `object_localized_23_en`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_23_en` AS select `object_query_23`.`oo_id` AS `oo_id`,`object_query_23`.`oo_classId` AS `oo_classId`,`object_query_23`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`object_localized_data_23`.`ooo_id` AS `ooo_id`,`object_localized_data_23`.`language` AS `language`,`object_localized_data_23`.`icon` AS `icon`,`object_localized_data_23`.`name` AS `name`,`object_localized_data_23`.`seoname` AS `seoname`,`object_localized_data_23`.`description` AS `description`,`object_localized_data_23`.`link` AS `link` from ((`object_query_23` join `objects` on((`objects`.`o_id` = `object_query_23`.`oo_id`))) left join `object_localized_data_23` on(((`object_query_23`.`oo_id` = `object_localized_data_23`.`ooo_id`) and (`object_localized_data_23`.`language` = 'en'))));

DROP VIEW IF EXISTS `object_localized_23_en_GB`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_23_en_GB` AS select `object_query_23`.`oo_id` AS `oo_id`,`object_query_23`.`oo_classId` AS `oo_classId`,`object_query_23`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`en_GB`.`ooo_id` AS `ooo_id`,`en_GB`.`language` AS `language`,`en_GB`.`icon` AS `icon`,`en_GB`.`name` AS `name`,`en_GB`.`seoname` AS `seoname`,`en_GB`.`description` AS `description`,`en_GB`.`link` AS `link`,`en_GB`.`images` AS `images`,`en_GB`.`documents` AS `documents`,`en_GB`.`videos` AS `videos`,`en_GB`.`downloads` AS `downloads` from ((`object_query_23` join `objects` on((`objects`.`o_id` = `object_query_23`.`oo_id`))) left join `object_localized_query_23_en_GB` `en_GB` on((1 and (`object_query_23`.`oo_id` = `en_GB`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_23_fr_FR`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_23_fr_FR` AS select `object_query_23`.`oo_id` AS `oo_id`,`object_query_23`.`oo_classId` AS `oo_classId`,`object_query_23`.`oo_className` AS `oo_className`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`objects`.`o_childrenSortBy` AS `o_childrenSortBy`,`objects`.`o_versionCount` AS `o_versionCount`,`fr_FR`.`ooo_id` AS `ooo_id`,`fr_FR`.`language` AS `language`,`fr_FR`.`icon` AS `icon`,`fr_FR`.`name` AS `name`,`fr_FR`.`seoname` AS `seoname`,`fr_FR`.`description` AS `description`,`fr_FR`.`link` AS `link`,`fr_FR`.`images` AS `images`,`fr_FR`.`documents` AS `documents`,`fr_FR`.`videos` AS `videos`,`fr_FR`.`downloads` AS `downloads` from ((`object_query_23` join `objects` on((`objects`.`o_id` = `object_query_23`.`oo_id`))) left join `object_localized_query_23_fr_FR` `fr_FR` on((1 and (`object_query_23`.`oo_id` = `fr_FR`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_35_de_AT`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_35_de_AT` AS select `object_query_35`.`oo_id` AS `oo_id`,`object_query_35`.`oo_classId` AS `oo_classId`,`object_query_35`.`oo_className` AS `oo_className`,`object_query_35`.`taxEntryCombinationType` AS `taxEntryCombinationType`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`de_AT`.`ooo_id` AS `ooo_id`,`de_AT`.`language` AS `language`,`de_AT`.`name` AS `name` from ((`object_query_35` join `objects` on((`objects`.`o_id` = `object_query_35`.`oo_id`))) left join `object_localized_query_35_de_AT` `de_AT` on((1 and (`object_query_35`.`oo_id` = `de_AT`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_35_en_GB`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_35_en_GB` AS select `object_query_35`.`oo_id` AS `oo_id`,`object_query_35`.`oo_classId` AS `oo_classId`,`object_query_35`.`oo_className` AS `oo_className`,`object_query_35`.`taxEntryCombinationType` AS `taxEntryCombinationType`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`en_GB`.`ooo_id` AS `ooo_id`,`en_GB`.`language` AS `language`,`en_GB`.`name` AS `name` from ((`object_query_35` join `objects` on((`objects`.`o_id` = `object_query_35`.`oo_id`))) left join `object_localized_query_35_en_GB` `en_GB` on((1 and (`object_query_35`.`oo_id` = `en_GB`.`ooo_id`))));

DROP VIEW IF EXISTS `object_localized_35_fr_FR`;
CREATE ALGORITHM=UNDEFINED  VIEW `object_localized_35_fr_FR` AS select `object_query_35`.`oo_id` AS `oo_id`,`object_query_35`.`oo_classId` AS `oo_classId`,`object_query_35`.`oo_className` AS `oo_className`,`object_query_35`.`taxEntryCombinationType` AS `taxEntryCombinationType`,`objects`.`o_id` AS `o_id`,`objects`.`o_parentId` AS `o_parentId`,`objects`.`o_type` AS `o_type`,`objects`.`o_key` AS `o_key`,`objects`.`o_path` AS `o_path`,`objects`.`o_index` AS `o_index`,`objects`.`o_published` AS `o_published`,`objects`.`o_creationDate` AS `o_creationDate`,`objects`.`o_modificationDate` AS `o_modificationDate`,`objects`.`o_userOwner` AS `o_userOwner`,`objects`.`o_userModification` AS `o_userModification`,`objects`.`o_classId` AS `o_classId`,`objects`.`o_className` AS `o_className`,`fr_FR`.`ooo_id` AS `ooo_id`,`fr_FR`.`language` AS `language`,`fr_FR`.`name` AS `name` from ((`object_query_35` join `objects` on((`objects`.`o_id` = `object_query_35`.`oo_id`))) left join `object_localized_query_35_fr_FR` `fr_FR` on((1 and (`object_query_35`.`oo_id` = `fr_FR`.`ooo_id`))));
