
SET NAMES utf8mb4;

INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('10961','15','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11235',NULL,'0',NULL,NULL,NULL,'false',NULL,'0',NULL,NULL);
INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11259','9','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11265',NULL,'0',NULL,NULL,NULL,'false',NULL,'0',NULL,NULL);
INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11266',NULL,'0',NULL,NULL,NULL,'false',NULL,'0',NULL,NULL);
INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11267',NULL,'0',NULL,NULL,NULL,NULL,NULL,'0',NULL,NULL);
INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11268',NULL,'0',NULL,NULL,NULL,'false',NULL,'0',NULL,NULL);
INSERT INTO object_store_7 (`oo_id`,`pageLimit`,`ajaxReload`,`limitOnFirstLoad`,`defaultOrderByInheritance`,`conditionsInheritance`,`filtersInheritance`,`similarityFieldsInheritance`,`infiniteScroll`,`orderByAsc`,`orderByDesc`) VALUES ('11275','9','1',NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL);
