
SET NAMES utf8mb4;

INSERT INTO object_collection_FilterNumberRangeSelection_7 (`o_id`,`index`,`fieldname`,`label`,`ranges__range1#from`,`ranges__range1#to`,`ranges__range2#from`,`ranges__range2#to`,`ranges__range3#from`,`ranges__range3#to`,`ranges__range4#from`,`ranges__range4#to`,`preSelectFrom`,`preSelectTo`,`scriptPath`,`unit`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11267','2','filters','Volume','0','20','21','40','41','60','61','0',NULL,NULL,'','l',NULL,'rucksacksVolume',NULL);
INSERT INTO object_collection_FilterNumberRangeSelection_7 (`o_id`,`index`,`fieldname`,`label`,`ranges__range1#from`,`ranges__range1#to`,`ranges__range2#from`,`ranges__range2#to`,`ranges__range3#from`,`ranges__range3#to`,`ranges__range4#from`,`ranges__range4#to`,`preSelectFrom`,`preSelectTo`,`scriptPath`,`unit`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11267','3','filters','Weight','0','1','1','2','2','3','3','0',NULL,NULL,'','kg',NULL,'rucksacksWeight',NULL);
INSERT INTO object_collection_FilterNumberRangeSelection_7 (`o_id`,`index`,`fieldname`,`label`,`ranges__range1#from`,`ranges__range1#to`,`ranges__range2#from`,`ranges__range2#to`,`ranges__range3#from`,`ranges__range3#to`,`ranges__range4#from`,`ranges__range4#to`,`preSelectFrom`,`preSelectTo`,`scriptPath`,`unit`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11267','4','filters','Load','0','5','5','10','10','15','15','0',NULL,NULL,'','kg',NULL,'rucksacksLoad',NULL);
INSERT INTO object_collection_FilterNumberRangeSelection_7 (`o_id`,`index`,`fieldname`,`label`,`ranges__range1#from`,`ranges__range1#to`,`ranges__range2#from`,`ranges__range2#to`,`ranges__range3#from`,`ranges__range3#to`,`ranges__range4#from`,`ranges__range4#to`,`preSelectFrom`,`preSelectTo`,`scriptPath`,`unit`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11268','1','filters','Width','0','50','50','80','80','0','0','0',NULL,NULL,'','cm',NULL,'matsWidth',NULL);
INSERT INTO object_collection_FilterNumberRangeSelection_7 (`o_id`,`index`,`fieldname`,`label`,`ranges__range1#from`,`ranges__range1#to`,`ranges__range2#from`,`ranges__range2#to`,`ranges__range3#from`,`ranges__range3#to`,`ranges__range4#from`,`ranges__range4#to`,`preSelectFrom`,`preSelectTo`,`scriptPath`,`unit`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11268','2','filters','Length','0','150','150','180','180','0','0','0',NULL,NULL,'','cm',NULL,'matsLength',NULL);
INSERT INTO object_collection_FilterNumberRangeSelection_7 (`o_id`,`index`,`fieldname`,`label`,`ranges__range1#from`,`ranges__range1#to`,`ranges__range2#from`,`ranges__range2#to`,`ranges__range3#from`,`ranges__range3#to`,`ranges__range4#from`,`ranges__range4#to`,`preSelectFrom`,`preSelectTo`,`scriptPath`,`unit`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11268','3','filters','Height','0','1','1','2','2','0','0','0',NULL,NULL,'','cm',NULL,'matsHeight',NULL);
