
SET NAMES utf8mb4;

INSERT INTO object_collection_FilterMultiSelect_7 (`o_id`,`index`,`fieldname`,`label`,`scriptPath`,`UseAndCondition`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11265','1','filters','TentPegs','Shop/filters/multiselect-notranslation.html.php','0',NULL,'tentTentPegs','');
INSERT INTO object_collection_FilterMultiSelect_7 (`o_id`,`index`,`fieldname`,`label`,`scriptPath`,`UseAndCondition`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11265','2','filters','WaterproofRain','Shop/filters/multiselect-notranslation.html.php','0',NULL,'tentWaterproofRain','');
INSERT INTO object_collection_FilterMultiSelect_7 (`o_id`,`index`,`fieldname`,`label`,`scriptPath`,`UseAndCondition`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11265','3','filters','WaterproofGround','Shop/filters/multiselect-notranslation.html.php','0',NULL,'tentWaterproofGround','');
INSERT INTO object_collection_FilterMultiSelect_7 (`o_id`,`index`,`fieldname`,`label`,`scriptPath`,`UseAndCondition`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11275','2','filters','TentPegs','Shop/filters/multiselect-notranslation.html.php','0',NULL,'tentTentPegs','');
INSERT INTO object_collection_FilterMultiSelect_7 (`o_id`,`index`,`fieldname`,`label`,`scriptPath`,`UseAndCondition`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11275','3','filters','WaterproofGround','Shop/filters/multiselect-notranslation.html.php','0',NULL,'tentWaterproofGround','');
INSERT INTO object_collection_FilterMultiSelect_7 (`o_id`,`index`,`fieldname`,`label`,`scriptPath`,`UseAndCondition`,`field__tenant`,`field__field`,`field__preSelect`) VALUES ('11275','4','filters','WaterproofRain','Shop/filters/multiselect-notranslation.html.php','0',NULL,'tentWaterproofRain','');
