
SET NAMES utf8mb4;

INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('1','','content','redirect','','','','a:0:{}','',NULL,NULL,'0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('3',NULL,'content','landing-page',NULL,'','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('4','','content','portal',NULL,'','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('14',NULL,'content','landing-page',NULL,'','','a:0:{}',NULL,NULL,',12,5,','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('15','','content','default',NULL,'Terms & Conditions','','a:0:{}','',NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('16','','content','default',NULL,'Special Functions implemented in this Demo','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('17',NULL,'content','default',NULL,'','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('18','','content','default','','Filterdefinitions','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('19','','content','default','','Marketing and Pricing Rules','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('20','','content','default','','Cross Selling','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('21','','content','default','','Targeting Groups','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('22','','content','default','','Outputchannels for Attributes','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('23','','content','default','','Landingpages','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('24','','content','landing-page','','Landingpage 2','','a:0:{}',NULL,NULL,',11,7,','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('51','','content','tenant-switches','','','','a:0:{}',NULL,NULL,',10,','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('54','','content','default','','','','a:0:{}',NULL,NULL,'','0');
INSERT INTO documents_page (`id`,`module`,`controller`,`action`,`template`,`title`,`description`,`metaData`,`prettyUrl`,`contentMasterDocumentId`,`targetGroupIds`,`legacy`) VALUES ('55','','content','default','','','','a:0:{}',NULL,NULL,'','0');
