
SET NAMES utf8mb4;

INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11972','paymentProvider','PREPAYMENT',NULL,'SUCCESS',NULL,NULL,NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11976','paymentProvider','PREPAYMENT',NULL,'SUCCESS',NULL,NULL,NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11980','paymentProvider','PAYPAL','2947632','SUCCESS','70.87','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11982','paymentProvider','PAYPAL','4240503','SUCCESS','12.79','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11986','paymentProvider','CCARD','15144502','SUCCESS','70.87','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11988','paymentProvider','SOFORTUEBERWEISUNG','1249621','SUCCESS','49.38','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11992','paymentProvider','INVOICE','12995718','SUCCESS','70.87','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('11994','paymentProvider','PREPAYMENT',NULL,'SUCCESS',NULL,NULL,NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12004','paymentProvider','SOFORTUEBERWEISUNG','3070820','SUCCESS','55.85','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12006','paymentProvider','CCARD','14824177','SUCCESS','105.85','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12008','paymentProvider','CCARD','13189259','SUCCESS','45.77','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12071','paymentProvider','PREPAYMENT',NULL,'SUCCESS',NULL,NULL,NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12073','paymentProvider','CCARD','10491672','SUCCESS','45.77','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12075','paymentProvider','CCARD','6421949','SUCCESS','98.86','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12077','paymentProvider','CCARD','11870650','SUCCESS','71.82','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12079','paymentProvider','PAYPAL','5125936','SUCCESS','94.49','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12081','paymentProvider','INVOICE','9924015','SUCCESS','12.79','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12184','paymentProvider','SOFORTUEBERWEISUNG','3834857','SUCCESS','1','EUR',NULL,NULL);
INSERT INTO object_brick_query_PaymentProviderWirecardSeamless_9 (`o_id`,`fieldname`,`auth_paymentType`,`auth_orderNumber`,`auth_paymentState`,`auth_amount`,`auth_currency`,`auth_gatewyReferenceNumber`,`configurationKey`) VALUES ('12209','paymentProvider','CCARD','8128180','SUCCESS','33.23','EUR',NULL,NULL);
