
SET NAMES utf8mb4;

INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('4846','specificAttributes','20','10','20','30','10','50','60','30','45','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6479','specificAttributes','40','30','40','4x Power LED',NULL,NULL,'IPX 4','2x AAA','64','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6480','specificAttributes','40','30','40','4x Power LED',NULL,NULL,'IPX 4','2x AAA','64','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6495','specificAttributes','55','40','100','2x Power LED','Boost LED 1W',NULL,'IPX 4','3x AAA, lithium compatible','88g','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6509','specificAttributes','75','60','80','4x Power LED','Boost LED 1 W',NULL,'IPX 4','3x AAA, lithium compatible','88','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6515','specificAttributes','75','60','80','4x Power LED','Boost LED 1 W',NULL,'IPX 4','3x AAA, lithium compatible','88','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6520','specificAttributes','25','25','25','3x Power LED',NULL,NULL,'IPX 4','2x AAA','64','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6542','specificAttributes','25','25','25','3x Power LED',NULL,NULL,'IPX 4','2x AAA','64','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('6544','specificAttributes','55','40','100','2x Power LED','Boost LED 1W',NULL,'IPX 4','3x AAA, lithium compatible','88g','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('9183','specificAttributes','100','70','60','4x Power LED','Boost LED 1W','Red LED','IPX 4','3x AAA, lithium compatible','89g','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('9184','specificAttributes','100','70','60','4x Power LED','Boost LED 1W','Red LED','IPX 4','3x AAA, lithium compatible','89g','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('9323','specificAttributes','100','70','60','4x Power LED','Boost LED 1W','Red LED','IPX 4','3x AAA, lithium compatible','89g','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('10507','specificAttributes','55','40','100','2x Power LED','Boost LED 1W',NULL,'IPX 4','3x AAA, lithium compatible','88g','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('10516','specificAttributes','75','60','80','4x Power LED','Boost LED 1 W',NULL,'IPX 4','3x AAA, lithium compatible','88','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('10520','specificAttributes','25','25','25','3x Power LED',NULL,NULL,'IPX 4','2x AAA','64','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('10524','specificAttributes','40','30','40','4x Power LED',NULL,NULL,'IPX 4','2x AAA','64','1','1');
INSERT INTO object_brick_query_featuresHeadlamps_12 (`o_id`,`fieldname`,`lumen`,`lightDistance`,`lightDuration`,`ledType`,`ledBoost`,`ledRed`,`waterResistant`,`batteries`,`weight`,`hasFlashingMode`,`isCeApproved`) VALUES ('11036','specificAttributes','20',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1');
